version: '2'
services:
  nginx:
    build:
      context: ./nginx
    image: reactjs_nginx
    container_name: reactjs_nginx_container
    ports:
      - "80:8080"
    volumes:
      - ./public:/wwwroot:ro
  webpack:
    build:
      context: ./webpack
    image: reactjs_webpack
    container_name: reactjs_webpack_container
    volumes:
      - ./src:/src:ro
      - ./public:/public:z